language: go

addons:
  apt:
    packages:
    # needed for the nfpm pipe:
    - rpm
    # needed for the snap pipe:
    - snapcraft

env:
# needed for the snap pipe:
  - PATH=/snap/bin:$PATH

script:
  - go test -race -v ./...

go:
  - 1.6
  - 1.7
  - 1.8
  - tip

matrix:
  allow_failures:
    - go: tip

install:
  - sudo snap install snapcraft --classic
  - go get github.com/xzyaoi/webtail

services:
  - docker

deploy:
  - provider: script
    skip_cleanup: true
    script: curl -sL https://git.io/goreleaser | bash
    on:
      tags: true
      condition: $TRAVIS_OS_NAME = linux